[tool.poetry]
name = "jrpyml"
version = "0.2.6"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16"
pandas = "^0.24.2"
matplotlib = "^3.1"
statsmodels = "^0.9.0"
scipy = "=1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
