[tool.poetry]
name = "keats"
version = "0.2.2"
description = "Utilities for managing version, changelogs, and project releases."
authors = ["jvrana <justin.vrana@gmail.com>"]
packages = [
    { include = "keats" },
    { include = "keat_scripts" }
]
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
fire = "^0.1.3"
termcolor = "^1.1"

[tool.poetry.dev-dependencies]
pre-commit = "^1.17"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pytest = "^5.0"

[tool.poetry.scripts]
keats = 'keats:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
